### ISSUE TITLE
yarn run tsoa routes - returns error

### ISSUE THREAD

**Issue by zaalgol** [tsoa-community/docs#20]
I implement step by step the example in [https://tsoa-community.github.io/docs/getting-started.html#initializing-our-project](https://tsoa-community.github.io/docs/getting-started.html#initializing-our-project), and get an error with yarn run tsoa routes

**Comment by zaalgol** [comment]
Building the routes file with:

    yarn run tsoa routes
    
returns error:

    yarn run v1.22.5
    $ C:\tsoa-project\node_modules\.bin\tsoa routes
    Generate routes error.
     Error: ENOENT: no such file or directory, lstat 'build'
        at Object.lstatSync (fs.js:1077:3)
        at RouteGenerator.<anonymous> (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:69:33)
        at step (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:44:23)
        at Object.next (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:25:53)
        at C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:19:71
        at new Promise (<anonymous>)
        at __awaiter (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:15:12)
        at RouteGenerator.GenerateRoutes (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:64:16)
        at RouteGenerator.<anonymous> (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:94:51)
        at step (C:\tsoa-project\node_modules\@tsoa\cli\dist\routeGeneration\routeGenerator.js:44:23) {
      errno: -4058,
      syscall: 'lstat',
      code: 'ENOENT',
      path: 'build'
    }
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by WoH** [comment]
Added a mkdir for the build to the getting started guide
